// OneSignal SDK MUST be imported at the very top for initial evaluation
importScripts('https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js');

/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkOnly } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

// Register ALL event listeners synchronously at the top level
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Deny list for API and external services
const networkOnlyDenylist = [
  /^\/api/,
  /\.supabase\.co/,
  /onesignal\.com/,
  /api\.onesignal\.com/
];

registerRoute(
  ({ url }) => networkOnlyDenylist.some(pattern => {
    if (typeof pattern === 'string') return url.href.includes(pattern);
    return pattern.test(url.href) || pattern.test(url.pathname);
  }),
  new NetworkOnly()
);

// Cache styles, scripts, and workers
registerRoute(
  ({ request }) => request.destination === 'style' || request.destination === 'script' || request.destination === 'worker',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);
